rounded rectangle
voxell-tech/bevy_motiongfx pull request #48
Opened 2024-05-27 08:25 UTC by aymey

related to #43 

> auto switching between rounded and non-rounded

how would we do this? seems polymorphic so rust traits would be the only option right?

2024-05-27 08:31 UTC, aymey commented
or a simpler solution would be a condition in `shape()` i.e.
```rust
impl VelloVector for VelloRect {
    fn shape(&self) -> impl kurbo::Shape {
       if self.radius == 0 { kurbo::Rect::new(...)}
       else { kurbo::RoundedRect::new(...)}
    }
}

```

2024-05-27 08:32 UTC, nixon-voxell commented
yeah, I was thinking maybe just a simple if statement? haha not sure if that would worth the performance cost tho?

2024-05-27 09:09 UTC, aymey commented
im currently struggling with object safety by return different types. Seems like a new `Shape` trait with object safety is necessary although it may lack features required for the objects manipulation.

As for performance, i **think** it would actually be much worse if we use return different types due to dynamic dispatch rather than if we just return a `RoundedRect` with a radius of 0 some of the time.

2024-05-27 09:16 UTC, nixon-voxell commented
Oh yes, of course, I have not thought of that! haha thanks for pointing it out, then I guess, the easiest solution would be the current implementation or add a new type `VelloRoundedRect` tho, I think the current implementation is more user friendly.

2024-05-27 09:19 UTC, aymey commented
I vote to keep the current implementation until https://github.com/linebender/kurbo/pull/331 gets merged then rewrite with that in mind

2024-05-27 13:12 UTC, nixon-voxell requested changes
Hey juz a tiny change to fix the rust fmt error, thanks!

2024-05-27 13:12 UTC, nixon-voxell commented on crates/bevy_vello_graphics/src/rect.rs
> +    pub radius: f64
```suggestion
    pub radius: f64,
```

2024-05-28 02:40 UTC, nixon-voxell approved these changes

2024-05-28 02:40 UTC, merged

2024-05-28 02:45 UTC, nixon-voxell commented
@aymey I also wanted to point out that your changes will be moved into the new repo I created: https://github.com/voxell-tech/bevy_vello_graphics.